#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DATA")]
	public partial class DB : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCategory(DATA.model.Category instance);
    partial void UpdateCategory(DATA.model.Category instance);
    partial void DeleteCategory(DATA.model.Category instance);
    partial void InsertProduct(DATA.model.Product instance);
    partial void UpdateProduct(DATA.model.Product instance);
    partial void DeleteProduct(DATA.model.Product instance);
    partial void InsertScales(DATA.model.Scales instance);
    partial void UpdateScales(DATA.model.Scales instance);
    partial void DeleteScales(DATA.model.Scales instance);
    #endregion
		
		public DB() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["DATAConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DB(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DB(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DATA.model.Category> Category
		{
			get
			{
				return this.GetTable<DATA.model.Category>();
			}
		}
		
		public System.Data.Linq.Table<DATA.model.Product> Product
		{
			get
			{
				return this.GetTable<DATA.model.Product>();
			}
		}
		
		public System.Data.Linq.Table<DATA.model.Scales> Scales
		{
			get
			{
				return this.GetTable<DATA.model.Scales>();
			}
		}
	}
}
namespace DATA.model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Category")]
	public partial class Category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _shop_id;
		
		private string _branch_id;
		
		private string _pos_no;
		
		private string _category_num;
		
		private string _category_name;
		
		private string _name_spell;
		
		private string _parent;
		
		private string _describ;
		
		private string _image;
		
		private string _product_count;
		
		private string _product_count_not_disabled;
		
		private System.Nullable<System.DateTime> _add_time;
		
		private string _add_user;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _update_user;
		
		private string _ver;
		
		private string _order_index;
		
		private string _images;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void Onshop_idChanging(string value);
    partial void Onshop_idChanged();
    partial void Onbranch_idChanging(string value);
    partial void Onbranch_idChanged();
    partial void Onpos_noChanging(string value);
    partial void Onpos_noChanged();
    partial void Oncategory_numChanging(string value);
    partial void Oncategory_numChanged();
    partial void Oncategory_nameChanging(string value);
    partial void Oncategory_nameChanged();
    partial void Onname_spellChanging(string value);
    partial void Onname_spellChanged();
    partial void OnparentChanging(string value);
    partial void OnparentChanged();
    partial void OndescribChanging(string value);
    partial void OndescribChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void Onproduct_countChanging(string value);
    partial void Onproduct_countChanged();
    partial void Onproduct_count_not_disabledChanging(string value);
    partial void Onproduct_count_not_disabledChanged();
    partial void Onadd_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onadd_timeChanged();
    partial void Onadd_userChanging(string value);
    partial void Onadd_userChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Onupdate_userChanging(string value);
    partial void Onupdate_userChanged();
    partial void OnverChanging(string value);
    partial void OnverChanged();
    partial void Onorder_indexChanging(string value);
    partial void Onorder_indexChanged();
    partial void OnimagesChanging(string value);
    partial void OnimagesChanged();
    #endregion
		
		public Category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shop_id", DbType="NVarChar(50)")]
		public string shop_id
		{
			get
			{
				return this._shop_id;
			}
			set
			{
				if ((this._shop_id != value))
				{
					this.Onshop_idChanging(value);
					this.SendPropertyChanging();
					this._shop_id = value;
					this.SendPropertyChanged("shop_id");
					this.Onshop_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch_id", DbType="NVarChar(50)")]
		public string branch_id
		{
			get
			{
				return this._branch_id;
			}
			set
			{
				if ((this._branch_id != value))
				{
					this.Onbranch_idChanging(value);
					this.SendPropertyChanging();
					this._branch_id = value;
					this.SendPropertyChanged("branch_id");
					this.Onbranch_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos_no", DbType="NVarChar(50)")]
		public string pos_no
		{
			get
			{
				return this._pos_no;
			}
			set
			{
				if ((this._pos_no != value))
				{
					this.Onpos_noChanging(value);
					this.SendPropertyChanging();
					this._pos_no = value;
					this.SendPropertyChanged("pos_no");
					this.Onpos_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_num", DbType="NVarChar(50)")]
		public string category_num
		{
			get
			{
				return this._category_num;
			}
			set
			{
				if ((this._category_num != value))
				{
					this.Oncategory_numChanging(value);
					this.SendPropertyChanging();
					this._category_num = value;
					this.SendPropertyChanged("category_num");
					this.Oncategory_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="NVarChar(255)")]
		public string category_name
		{
			get
			{
				return this._category_name;
			}
			set
			{
				if ((this._category_name != value))
				{
					this.Oncategory_nameChanging(value);
					this.SendPropertyChanging();
					this._category_name = value;
					this.SendPropertyChanged("category_name");
					this.Oncategory_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_spell", DbType="NVarChar(255)")]
		public string name_spell
		{
			get
			{
				return this._name_spell;
			}
			set
			{
				if ((this._name_spell != value))
				{
					this.Onname_spellChanging(value);
					this.SendPropertyChanging();
					this._name_spell = value;
					this.SendPropertyChanged("name_spell");
					this.Onname_spellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_parent", DbType="NVarChar(50)")]
		public string parent
		{
			get
			{
				return this._parent;
			}
			set
			{
				if ((this._parent != value))
				{
					this.OnparentChanging(value);
					this.SendPropertyChanging();
					this._parent = value;
					this.SendPropertyChanged("parent");
					this.OnparentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_describ", DbType="NVarChar(255)")]
		public string describ
		{
			get
			{
				return this._describ;
			}
			set
			{
				if ((this._describ != value))
				{
					this.OndescribChanging(value);
					this.SendPropertyChanging();
					this._describ = value;
					this.SendPropertyChanged("describ");
					this.OndescribChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(225)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_count", DbType="NVarChar(50)")]
		public string product_count
		{
			get
			{
				return this._product_count;
			}
			set
			{
				if ((this._product_count != value))
				{
					this.Onproduct_countChanging(value);
					this.SendPropertyChanging();
					this._product_count = value;
					this.SendPropertyChanged("product_count");
					this.Onproduct_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_count_not_disabled", DbType="NVarChar(50)")]
		public string product_count_not_disabled
		{
			get
			{
				return this._product_count_not_disabled;
			}
			set
			{
				if ((this._product_count_not_disabled != value))
				{
					this.Onproduct_count_not_disabledChanging(value);
					this.SendPropertyChanging();
					this._product_count_not_disabled = value;
					this.SendPropertyChanged("product_count_not_disabled");
					this.Onproduct_count_not_disabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_user", DbType="NVarChar(50)")]
		public string add_user
		{
			get
			{
				return this._add_user;
			}
			set
			{
				if ((this._add_user != value))
				{
					this.Onadd_userChanging(value);
					this.SendPropertyChanging();
					this._add_user = value;
					this.SendPropertyChanged("add_user");
					this.Onadd_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_user", DbType="NVarChar(50)")]
		public string update_user
		{
			get
			{
				return this._update_user;
			}
			set
			{
				if ((this._update_user != value))
				{
					this.Onupdate_userChanging(value);
					this.SendPropertyChanging();
					this._update_user = value;
					this.SendPropertyChanged("update_user");
					this.Onupdate_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ver", DbType="NVarChar(50)")]
		public string ver
		{
			get
			{
				return this._ver;
			}
			set
			{
				if ((this._ver != value))
				{
					this.OnverChanging(value);
					this.SendPropertyChanging();
					this._ver = value;
					this.SendPropertyChanged("ver");
					this.OnverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_index", DbType="NVarChar(50)")]
		public string order_index
		{
			get
			{
				return this._order_index;
			}
			set
			{
				if ((this._order_index != value))
				{
					this.Onorder_indexChanging(value);
					this.SendPropertyChanging();
					this._order_index = value;
					this.SendPropertyChanged("order_index");
					this.Onorder_indexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_images", DbType="NVarChar(MAX)")]
		public string images
		{
			get
			{
				return this._images;
			}
			set
			{
				if ((this._images != value))
				{
					this.OnimagesChanging(value);
					this.SendPropertyChanging();
					this._images = value;
					this.SendPropertyChanged("images");
					this.OnimagesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Product")]
	public partial class Product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _shop_id;
		
		private string _branch_id;
		
		private string _pos_no;
		
		private string _product_num;
		
		private string _taste;
		
		private string _barcode;
		
		private string _barcode_format;
		
		private string _product_name;
		
		private string _name_spell;
		
		private string _abbr;
		
		private string _abbr_spell;
		
		private string _category;
		
		private string _department;
		
		private string _pcs_flag;
		
		private string _default_pcs;
		
		private string _unit_text;
		
		private string _tare_num;
		
		private string _tare;
		
		private string _p_tare_unit;
		
		private string _stock;
		
		private string _stock_low;
		
		private string _stock_top;
		
		private string _FCL_ratio;
		
		private string _score_type;
		
		private string _score_ratio;
		
		private string _exchange_score;
		
		private string _price_lowest;
		
		private string _price;
		
		private string _price_vip1;
		
		private string _price_vip2;
		
		private string _price_vip3;
		
		private string _group_qty;
		
		private string _group_price;
		
		private string _priceUnit;
		
		private string _changePrice;
		
		private string _discount;
		
		private string _tax_num;
		
		private string _ingredient;
		
		private string _period;
		
		private string _recommend;
		
		private string _labelFormat;
		
		private string _trace;
		
		private string _image;
		
		private string _area;
		
		private string _temp_index;
		
		private string _temp_text;
		
		private string _remark1;
		
		private string _remark2;
		
		private string _audio;
		
		private string _disabled;
		
		private string _select_times;
		
		private System.Nullable<System.DateTime> _add_time;
		
		private string _add_user;
		
		private System.Nullable<System.DateTime> _update_time;
		
		private string _update_user;
		
		private string _ver;
		
		private string _show_byHDMI;
		
		private string _HDMI_mode;
		
		private string _mark_num;
		
		private string _etag_id;
		
		private string _item_id;
		
		private string _sku_id;
		
		private string _kill_data;
		
		private string _packing_data;
		
		private string _best_before_data;
		
		private string _used_data;
		
		private string _nutritional;
		
		private string _produced;
		
		private string _remark3;
		
		private string _remark4;
		
		private string _remark5;
		
		private string _remark6;
		
		private string _remark7;
		
		private string _remark8;
		
		private string _Images;
		
		private string _freeimage;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void Onshop_idChanging(string value);
    partial void Onshop_idChanged();
    partial void Onbranch_idChanging(string value);
    partial void Onbranch_idChanged();
    partial void Onpos_noChanging(string value);
    partial void Onpos_noChanged();
    partial void Onproduct_numChanging(string value);
    partial void Onproduct_numChanged();
    partial void OntasteChanging(string value);
    partial void OntasteChanged();
    partial void OnbarcodeChanging(string value);
    partial void OnbarcodeChanged();
    partial void Onbarcode_formatChanging(string value);
    partial void Onbarcode_formatChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onname_spellChanging(string value);
    partial void Onname_spellChanged();
    partial void OnabbrChanging(string value);
    partial void OnabbrChanged();
    partial void Onabbr_spellChanging(string value);
    partial void Onabbr_spellChanged();
    partial void OncategoryChanging(string value);
    partial void OncategoryChanged();
    partial void OndepartmentChanging(string value);
    partial void OndepartmentChanged();
    partial void Onpcs_flagChanging(string value);
    partial void Onpcs_flagChanged();
    partial void Ondefault_pcsChanging(string value);
    partial void Ondefault_pcsChanged();
    partial void Onunit_textChanging(string value);
    partial void Onunit_textChanged();
    partial void Ontare_numChanging(string value);
    partial void Ontare_numChanged();
    partial void OntareChanging(string value);
    partial void OntareChanged();
    partial void Onp_tare_unitChanging(string value);
    partial void Onp_tare_unitChanged();
    partial void OnstockChanging(string value);
    partial void OnstockChanged();
    partial void Onstock_lowChanging(string value);
    partial void Onstock_lowChanged();
    partial void Onstock_topChanging(string value);
    partial void Onstock_topChanged();
    partial void OnFCL_ratioChanging(string value);
    partial void OnFCL_ratioChanged();
    partial void Onscore_typeChanging(string value);
    partial void Onscore_typeChanged();
    partial void Onscore_ratioChanging(string value);
    partial void Onscore_ratioChanged();
    partial void Onexchange_scoreChanging(string value);
    partial void Onexchange_scoreChanged();
    partial void Onprice_lowestChanging(string value);
    partial void Onprice_lowestChanged();
    partial void OnpriceChanging(string value);
    partial void OnpriceChanged();
    partial void Onprice_vip1Changing(string value);
    partial void Onprice_vip1Changed();
    partial void Onprice_vip2Changing(string value);
    partial void Onprice_vip2Changed();
    partial void Onprice_vip3Changing(string value);
    partial void Onprice_vip3Changed();
    partial void Ongroup_qtyChanging(string value);
    partial void Ongroup_qtyChanged();
    partial void Ongroup_priceChanging(string value);
    partial void Ongroup_priceChanged();
    partial void OnpriceUnitChanging(string value);
    partial void OnpriceUnitChanged();
    partial void OnchangePriceChanging(string value);
    partial void OnchangePriceChanged();
    partial void OndiscountChanging(string value);
    partial void OndiscountChanged();
    partial void Ontax_numChanging(string value);
    partial void Ontax_numChanged();
    partial void OningredientChanging(string value);
    partial void OningredientChanged();
    partial void OnperiodChanging(string value);
    partial void OnperiodChanged();
    partial void OnrecommendChanging(string value);
    partial void OnrecommendChanged();
    partial void OnlabelFormatChanging(string value);
    partial void OnlabelFormatChanged();
    partial void OntraceChanging(string value);
    partial void OntraceChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnareaChanging(string value);
    partial void OnareaChanged();
    partial void Ontemp_indexChanging(string value);
    partial void Ontemp_indexChanged();
    partial void Ontemp_textChanging(string value);
    partial void Ontemp_textChanged();
    partial void Onremark1Changing(string value);
    partial void Onremark1Changed();
    partial void Onremark2Changing(string value);
    partial void Onremark2Changed();
    partial void OnaudioChanging(string value);
    partial void OnaudioChanged();
    partial void OndisabledChanging(string value);
    partial void OndisabledChanged();
    partial void Onselect_timesChanging(string value);
    partial void Onselect_timesChanged();
    partial void Onadd_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onadd_timeChanged();
    partial void Onadd_userChanging(string value);
    partial void Onadd_userChanged();
    partial void Onupdate_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_timeChanged();
    partial void Onupdate_userChanging(string value);
    partial void Onupdate_userChanged();
    partial void OnverChanging(string value);
    partial void OnverChanged();
    partial void Onshow_byHDMIChanging(string value);
    partial void Onshow_byHDMIChanged();
    partial void OnHDMI_modeChanging(string value);
    partial void OnHDMI_modeChanged();
    partial void Onmark_numChanging(string value);
    partial void Onmark_numChanged();
    partial void Onetag_idChanging(string value);
    partial void Onetag_idChanged();
    partial void Onitem_idChanging(string value);
    partial void Onitem_idChanged();
    partial void Onsku_idChanging(string value);
    partial void Onsku_idChanged();
    partial void Onkill_dataChanging(string value);
    partial void Onkill_dataChanged();
    partial void Onpacking_dataChanging(string value);
    partial void Onpacking_dataChanged();
    partial void Onbest_before_dataChanging(string value);
    partial void Onbest_before_dataChanged();
    partial void Onused_dataChanging(string value);
    partial void Onused_dataChanged();
    partial void OnnutritionalChanging(string value);
    partial void OnnutritionalChanged();
    partial void OnproducedChanging(string value);
    partial void OnproducedChanged();
    partial void Onremark3Changing(string value);
    partial void Onremark3Changed();
    partial void Onremark4Changing(string value);
    partial void Onremark4Changed();
    partial void Onremark5Changing(string value);
    partial void Onremark5Changed();
    partial void Onremark6Changing(string value);
    partial void Onremark6Changed();
    partial void Onremark7Changing(string value);
    partial void Onremark7Changed();
    partial void Onremark8Changing(string value);
    partial void Onremark8Changed();
    partial void OnImagesChanging(string value);
    partial void OnImagesChanged();
    partial void OnfreeimageChanging(string value);
    partial void OnfreeimageChanged();
    #endregion
		
		public Product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shop_id", DbType="NVarChar(50)")]
		public string shop_id
		{
			get
			{
				return this._shop_id;
			}
			set
			{
				if ((this._shop_id != value))
				{
					this.Onshop_idChanging(value);
					this.SendPropertyChanging();
					this._shop_id = value;
					this.SendPropertyChanged("shop_id");
					this.Onshop_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_branch_id", DbType="NVarChar(50)")]
		public string branch_id
		{
			get
			{
				return this._branch_id;
			}
			set
			{
				if ((this._branch_id != value))
				{
					this.Onbranch_idChanging(value);
					this.SendPropertyChanging();
					this._branch_id = value;
					this.SendPropertyChanged("branch_id");
					this.Onbranch_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos_no", DbType="NVarChar(50)")]
		public string pos_no
		{
			get
			{
				return this._pos_no;
			}
			set
			{
				if ((this._pos_no != value))
				{
					this.Onpos_noChanging(value);
					this.SendPropertyChanging();
					this._pos_no = value;
					this.SendPropertyChanged("pos_no");
					this.Onpos_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_num", DbType="NVarChar(50)")]
		public string product_num
		{
			get
			{
				return this._product_num;
			}
			set
			{
				if ((this._product_num != value))
				{
					this.Onproduct_numChanging(value);
					this.SendPropertyChanging();
					this._product_num = value;
					this.SendPropertyChanged("product_num");
					this.Onproduct_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taste", DbType="NVarChar(50)")]
		public string taste
		{
			get
			{
				return this._taste;
			}
			set
			{
				if ((this._taste != value))
				{
					this.OntasteChanging(value);
					this.SendPropertyChanging();
					this._taste = value;
					this.SendPropertyChanged("taste");
					this.OntasteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode", DbType="NVarChar(50)")]
		public string barcode
		{
			get
			{
				return this._barcode;
			}
			set
			{
				if ((this._barcode != value))
				{
					this.OnbarcodeChanging(value);
					this.SendPropertyChanging();
					this._barcode = value;
					this.SendPropertyChanged("barcode");
					this.OnbarcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_barcode_format", DbType="NVarChar(50)")]
		public string barcode_format
		{
			get
			{
				return this._barcode_format;
			}
			set
			{
				if ((this._barcode_format != value))
				{
					this.Onbarcode_formatChanging(value);
					this.SendPropertyChanging();
					this._barcode_format = value;
					this.SendPropertyChanged("barcode_format");
					this.Onbarcode_formatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(MAX)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_spell", DbType="NVarChar(MAX)")]
		public string name_spell
		{
			get
			{
				return this._name_spell;
			}
			set
			{
				if ((this._name_spell != value))
				{
					this.Onname_spellChanging(value);
					this.SendPropertyChanging();
					this._name_spell = value;
					this.SendPropertyChanged("name_spell");
					this.Onname_spellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abbr", DbType="NVarChar(MAX)")]
		public string abbr
		{
			get
			{
				return this._abbr;
			}
			set
			{
				if ((this._abbr != value))
				{
					this.OnabbrChanging(value);
					this.SendPropertyChanging();
					this._abbr = value;
					this.SendPropertyChanged("abbr");
					this.OnabbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abbr_spell", DbType="NVarChar(MAX)")]
		public string abbr_spell
		{
			get
			{
				return this._abbr_spell;
			}
			set
			{
				if ((this._abbr_spell != value))
				{
					this.Onabbr_spellChanging(value);
					this.SendPropertyChanging();
					this._abbr_spell = value;
					this.SendPropertyChanged("abbr_spell");
					this.Onabbr_spellChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="NVarChar(50)")]
		public string category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this.OncategoryChanging(value);
					this.SendPropertyChanging();
					this._category = value;
					this.SendPropertyChanged("category");
					this.OncategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_department", DbType="NVarChar(50)")]
		public string department
		{
			get
			{
				return this._department;
			}
			set
			{
				if ((this._department != value))
				{
					this.OndepartmentChanging(value);
					this.SendPropertyChanging();
					this._department = value;
					this.SendPropertyChanged("department");
					this.OndepartmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pcs_flag", DbType="NVarChar(50)")]
		public string pcs_flag
		{
			get
			{
				return this._pcs_flag;
			}
			set
			{
				if ((this._pcs_flag != value))
				{
					this.Onpcs_flagChanging(value);
					this.SendPropertyChanging();
					this._pcs_flag = value;
					this.SendPropertyChanged("pcs_flag");
					this.Onpcs_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_default_pcs", DbType="NVarChar(50)")]
		public string default_pcs
		{
			get
			{
				return this._default_pcs;
			}
			set
			{
				if ((this._default_pcs != value))
				{
					this.Ondefault_pcsChanging(value);
					this.SendPropertyChanging();
					this._default_pcs = value;
					this.SendPropertyChanged("default_pcs");
					this.Ondefault_pcsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit_text", DbType="NVarChar(50)")]
		public string unit_text
		{
			get
			{
				return this._unit_text;
			}
			set
			{
				if ((this._unit_text != value))
				{
					this.Onunit_textChanging(value);
					this.SendPropertyChanging();
					this._unit_text = value;
					this.SendPropertyChanged("unit_text");
					this.Onunit_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tare_num", DbType="NVarChar(50)")]
		public string tare_num
		{
			get
			{
				return this._tare_num;
			}
			set
			{
				if ((this._tare_num != value))
				{
					this.Ontare_numChanging(value);
					this.SendPropertyChanging();
					this._tare_num = value;
					this.SendPropertyChanged("tare_num");
					this.Ontare_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tare", DbType="NVarChar(50)")]
		public string tare
		{
			get
			{
				return this._tare;
			}
			set
			{
				if ((this._tare != value))
				{
					this.OntareChanging(value);
					this.SendPropertyChanging();
					this._tare = value;
					this.SendPropertyChanged("tare");
					this.OntareChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_p_tare_unit", DbType="NVarChar(50)")]
		public string p_tare_unit
		{
			get
			{
				return this._p_tare_unit;
			}
			set
			{
				if ((this._p_tare_unit != value))
				{
					this.Onp_tare_unitChanging(value);
					this.SendPropertyChanging();
					this._p_tare_unit = value;
					this.SendPropertyChanged("p_tare_unit");
					this.Onp_tare_unitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock", DbType="NVarChar(50)")]
		public string stock
		{
			get
			{
				return this._stock;
			}
			set
			{
				if ((this._stock != value))
				{
					this.OnstockChanging(value);
					this.SendPropertyChanging();
					this._stock = value;
					this.SendPropertyChanged("stock");
					this.OnstockChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_low", DbType="NVarChar(50)")]
		public string stock_low
		{
			get
			{
				return this._stock_low;
			}
			set
			{
				if ((this._stock_low != value))
				{
					this.Onstock_lowChanging(value);
					this.SendPropertyChanging();
					this._stock_low = value;
					this.SendPropertyChanged("stock_low");
					this.Onstock_lowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stock_top", DbType="NVarChar(50)")]
		public string stock_top
		{
			get
			{
				return this._stock_top;
			}
			set
			{
				if ((this._stock_top != value))
				{
					this.Onstock_topChanging(value);
					this.SendPropertyChanging();
					this._stock_top = value;
					this.SendPropertyChanged("stock_top");
					this.Onstock_topChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FCL_ratio", DbType="NVarChar(50)")]
		public string FCL_ratio
		{
			get
			{
				return this._FCL_ratio;
			}
			set
			{
				if ((this._FCL_ratio != value))
				{
					this.OnFCL_ratioChanging(value);
					this.SendPropertyChanging();
					this._FCL_ratio = value;
					this.SendPropertyChanged("FCL_ratio");
					this.OnFCL_ratioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score_type", DbType="NVarChar(50)")]
		public string score_type
		{
			get
			{
				return this._score_type;
			}
			set
			{
				if ((this._score_type != value))
				{
					this.Onscore_typeChanging(value);
					this.SendPropertyChanging();
					this._score_type = value;
					this.SendPropertyChanged("score_type");
					this.Onscore_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_score_ratio", DbType="NVarChar(50)")]
		public string score_ratio
		{
			get
			{
				return this._score_ratio;
			}
			set
			{
				if ((this._score_ratio != value))
				{
					this.Onscore_ratioChanging(value);
					this.SendPropertyChanging();
					this._score_ratio = value;
					this.SendPropertyChanged("score_ratio");
					this.Onscore_ratioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_exchange_score", DbType="NVarChar(50)")]
		public string exchange_score
		{
			get
			{
				return this._exchange_score;
			}
			set
			{
				if ((this._exchange_score != value))
				{
					this.Onexchange_scoreChanging(value);
					this.SendPropertyChanging();
					this._exchange_score = value;
					this.SendPropertyChanged("exchange_score");
					this.Onexchange_scoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_lowest", DbType="NVarChar(50)")]
		public string price_lowest
		{
			get
			{
				return this._price_lowest;
			}
			set
			{
				if ((this._price_lowest != value))
				{
					this.Onprice_lowestChanging(value);
					this.SendPropertyChanging();
					this._price_lowest = value;
					this.SendPropertyChanged("price_lowest");
					this.Onprice_lowestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="NVarChar(50)")]
		public string price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_vip1", DbType="NVarChar(50)")]
		public string price_vip1
		{
			get
			{
				return this._price_vip1;
			}
			set
			{
				if ((this._price_vip1 != value))
				{
					this.Onprice_vip1Changing(value);
					this.SendPropertyChanging();
					this._price_vip1 = value;
					this.SendPropertyChanged("price_vip1");
					this.Onprice_vip1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_vip2", DbType="NVarChar(50)")]
		public string price_vip2
		{
			get
			{
				return this._price_vip2;
			}
			set
			{
				if ((this._price_vip2 != value))
				{
					this.Onprice_vip2Changing(value);
					this.SendPropertyChanging();
					this._price_vip2 = value;
					this.SendPropertyChanged("price_vip2");
					this.Onprice_vip2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price_vip3", DbType="NVarChar(50)")]
		public string price_vip3
		{
			get
			{
				return this._price_vip3;
			}
			set
			{
				if ((this._price_vip3 != value))
				{
					this.Onprice_vip3Changing(value);
					this.SendPropertyChanging();
					this._price_vip3 = value;
					this.SendPropertyChanged("price_vip3");
					this.Onprice_vip3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_qty", DbType="NVarChar(50)")]
		public string group_qty
		{
			get
			{
				return this._group_qty;
			}
			set
			{
				if ((this._group_qty != value))
				{
					this.Ongroup_qtyChanging(value);
					this.SendPropertyChanging();
					this._group_qty = value;
					this.SendPropertyChanged("group_qty");
					this.Ongroup_qtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_price", DbType="NVarChar(50)")]
		public string group_price
		{
			get
			{
				return this._group_price;
			}
			set
			{
				if ((this._group_price != value))
				{
					this.Ongroup_priceChanging(value);
					this.SendPropertyChanging();
					this._group_price = value;
					this.SendPropertyChanged("group_price");
					this.Ongroup_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priceUnit", DbType="NVarChar(50)")]
		public string priceUnit
		{
			get
			{
				return this._priceUnit;
			}
			set
			{
				if ((this._priceUnit != value))
				{
					this.OnpriceUnitChanging(value);
					this.SendPropertyChanging();
					this._priceUnit = value;
					this.SendPropertyChanged("priceUnit");
					this.OnpriceUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_changePrice", DbType="NVarChar(50)")]
		public string changePrice
		{
			get
			{
				return this._changePrice;
			}
			set
			{
				if ((this._changePrice != value))
				{
					this.OnchangePriceChanging(value);
					this.SendPropertyChanging();
					this._changePrice = value;
					this.SendPropertyChanged("changePrice");
					this.OnchangePriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount", DbType="NVarChar(50)")]
		public string discount
		{
			get
			{
				return this._discount;
			}
			set
			{
				if ((this._discount != value))
				{
					this.OndiscountChanging(value);
					this.SendPropertyChanging();
					this._discount = value;
					this.SendPropertyChanged("discount");
					this.OndiscountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tax_num", DbType="NVarChar(50)")]
		public string tax_num
		{
			get
			{
				return this._tax_num;
			}
			set
			{
				if ((this._tax_num != value))
				{
					this.Ontax_numChanging(value);
					this.SendPropertyChanging();
					this._tax_num = value;
					this.SendPropertyChanged("tax_num");
					this.Ontax_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingredient", DbType="NVarChar(MAX)")]
		public string ingredient
		{
			get
			{
				return this._ingredient;
			}
			set
			{
				if ((this._ingredient != value))
				{
					this.OningredientChanging(value);
					this.SendPropertyChanging();
					this._ingredient = value;
					this.SendPropertyChanged("ingredient");
					this.OningredientChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_period", DbType="NVarChar(50)")]
		public string period
		{
			get
			{
				return this._period;
			}
			set
			{
				if ((this._period != value))
				{
					this.OnperiodChanging(value);
					this.SendPropertyChanging();
					this._period = value;
					this.SendPropertyChanged("period");
					this.OnperiodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recommend", DbType="NVarChar(50)")]
		public string recommend
		{
			get
			{
				return this._recommend;
			}
			set
			{
				if ((this._recommend != value))
				{
					this.OnrecommendChanging(value);
					this.SendPropertyChanging();
					this._recommend = value;
					this.SendPropertyChanged("recommend");
					this.OnrecommendChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_labelFormat", DbType="NVarChar(50)")]
		public string labelFormat
		{
			get
			{
				return this._labelFormat;
			}
			set
			{
				if ((this._labelFormat != value))
				{
					this.OnlabelFormatChanging(value);
					this.SendPropertyChanging();
					this._labelFormat = value;
					this.SendPropertyChanged("labelFormat");
					this.OnlabelFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trace", DbType="NVarChar(50)")]
		public string trace
		{
			get
			{
				return this._trace;
			}
			set
			{
				if ((this._trace != value))
				{
					this.OntraceChanging(value);
					this.SendPropertyChanging();
					this._trace = value;
					this.SendPropertyChanged("trace");
					this.OntraceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="NVarChar(50)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="NVarChar(50)")]
		public string area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this.OnareaChanging(value);
					this.SendPropertyChanging();
					this._area = value;
					this.SendPropertyChanged("area");
					this.OnareaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temp_index", DbType="NVarChar(50)")]
		public string temp_index
		{
			get
			{
				return this._temp_index;
			}
			set
			{
				if ((this._temp_index != value))
				{
					this.Ontemp_indexChanging(value);
					this.SendPropertyChanging();
					this._temp_index = value;
					this.SendPropertyChanged("temp_index");
					this.Ontemp_indexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temp_text", DbType="NVarChar(50)")]
		public string temp_text
		{
			get
			{
				return this._temp_text;
			}
			set
			{
				if ((this._temp_text != value))
				{
					this.Ontemp_textChanging(value);
					this.SendPropertyChanging();
					this._temp_text = value;
					this.SendPropertyChanged("temp_text");
					this.Ontemp_textChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark1", DbType="NVarChar(MAX)")]
		public string remark1
		{
			get
			{
				return this._remark1;
			}
			set
			{
				if ((this._remark1 != value))
				{
					this.Onremark1Changing(value);
					this.SendPropertyChanging();
					this._remark1 = value;
					this.SendPropertyChanged("remark1");
					this.Onremark1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark2", DbType="NVarChar(MAX)")]
		public string remark2
		{
			get
			{
				return this._remark2;
			}
			set
			{
				if ((this._remark2 != value))
				{
					this.Onremark2Changing(value);
					this.SendPropertyChanging();
					this._remark2 = value;
					this.SendPropertyChanged("remark2");
					this.Onremark2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_audio", DbType="NVarChar(50)")]
		public string audio
		{
			get
			{
				return this._audio;
			}
			set
			{
				if ((this._audio != value))
				{
					this.OnaudioChanging(value);
					this.SendPropertyChanging();
					this._audio = value;
					this.SendPropertyChanged("audio");
					this.OnaudioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_disabled", DbType="NVarChar(50)")]
		public string disabled
		{
			get
			{
				return this._disabled;
			}
			set
			{
				if ((this._disabled != value))
				{
					this.OndisabledChanging(value);
					this.SendPropertyChanging();
					this._disabled = value;
					this.SendPropertyChanged("disabled");
					this.OndisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_select_times", DbType="NVarChar(50)")]
		public string select_times
		{
			get
			{
				return this._select_times;
			}
			set
			{
				if ((this._select_times != value))
				{
					this.Onselect_timesChanging(value);
					this.SendPropertyChanging();
					this._select_times = value;
					this.SendPropertyChanged("select_times");
					this.Onselect_timesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> add_time
		{
			get
			{
				return this._add_time;
			}
			set
			{
				if ((this._add_time != value))
				{
					this.Onadd_timeChanging(value);
					this.SendPropertyChanging();
					this._add_time = value;
					this.SendPropertyChanged("add_time");
					this.Onadd_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_add_user", DbType="NVarChar(50)")]
		public string add_user
		{
			get
			{
				return this._add_user;
			}
			set
			{
				if ((this._add_user != value))
				{
					this.Onadd_userChanging(value);
					this.SendPropertyChanging();
					this._add_user = value;
					this.SendPropertyChanged("add_user");
					this.Onadd_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_time
		{
			get
			{
				return this._update_time;
			}
			set
			{
				if ((this._update_time != value))
				{
					this.Onupdate_timeChanging(value);
					this.SendPropertyChanging();
					this._update_time = value;
					this.SendPropertyChanged("update_time");
					this.Onupdate_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_user", DbType="NVarChar(50)")]
		public string update_user
		{
			get
			{
				return this._update_user;
			}
			set
			{
				if ((this._update_user != value))
				{
					this.Onupdate_userChanging(value);
					this.SendPropertyChanging();
					this._update_user = value;
					this.SendPropertyChanged("update_user");
					this.Onupdate_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ver", DbType="NVarChar(50)")]
		public string ver
		{
			get
			{
				return this._ver;
			}
			set
			{
				if ((this._ver != value))
				{
					this.OnverChanging(value);
					this.SendPropertyChanging();
					this._ver = value;
					this.SendPropertyChanged("ver");
					this.OnverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_show_byHDMI", DbType="NVarChar(50)")]
		public string show_byHDMI
		{
			get
			{
				return this._show_byHDMI;
			}
			set
			{
				if ((this._show_byHDMI != value))
				{
					this.Onshow_byHDMIChanging(value);
					this.SendPropertyChanging();
					this._show_byHDMI = value;
					this.SendPropertyChanged("show_byHDMI");
					this.Onshow_byHDMIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HDMI_mode", DbType="NVarChar(50)")]
		public string HDMI_mode
		{
			get
			{
				return this._HDMI_mode;
			}
			set
			{
				if ((this._HDMI_mode != value))
				{
					this.OnHDMI_modeChanging(value);
					this.SendPropertyChanging();
					this._HDMI_mode = value;
					this.SendPropertyChanged("HDMI_mode");
					this.OnHDMI_modeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mark_num", DbType="NVarChar(50)")]
		public string mark_num
		{
			get
			{
				return this._mark_num;
			}
			set
			{
				if ((this._mark_num != value))
				{
					this.Onmark_numChanging(value);
					this.SendPropertyChanging();
					this._mark_num = value;
					this.SendPropertyChanged("mark_num");
					this.Onmark_numChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_etag_id", DbType="NVarChar(50)")]
		public string etag_id
		{
			get
			{
				return this._etag_id;
			}
			set
			{
				if ((this._etag_id != value))
				{
					this.Onetag_idChanging(value);
					this.SendPropertyChanging();
					this._etag_id = value;
					this.SendPropertyChanged("etag_id");
					this.Onetag_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item_id", DbType="NVarChar(50)")]
		public string item_id
		{
			get
			{
				return this._item_id;
			}
			set
			{
				if ((this._item_id != value))
				{
					this.Onitem_idChanging(value);
					this.SendPropertyChanging();
					this._item_id = value;
					this.SendPropertyChanged("item_id");
					this.Onitem_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sku_id", DbType="NVarChar(50)")]
		public string sku_id
		{
			get
			{
				return this._sku_id;
			}
			set
			{
				if ((this._sku_id != value))
				{
					this.Onsku_idChanging(value);
					this.SendPropertyChanging();
					this._sku_id = value;
					this.SendPropertyChanged("sku_id");
					this.Onsku_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kill_data", DbType="NVarChar(50)")]
		public string kill_data
		{
			get
			{
				return this._kill_data;
			}
			set
			{
				if ((this._kill_data != value))
				{
					this.Onkill_dataChanging(value);
					this.SendPropertyChanging();
					this._kill_data = value;
					this.SendPropertyChanged("kill_data");
					this.Onkill_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_packing_data", DbType="NVarChar(50)")]
		public string packing_data
		{
			get
			{
				return this._packing_data;
			}
			set
			{
				if ((this._packing_data != value))
				{
					this.Onpacking_dataChanging(value);
					this.SendPropertyChanging();
					this._packing_data = value;
					this.SendPropertyChanged("packing_data");
					this.Onpacking_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_best_before_data", DbType="NVarChar(50)")]
		public string best_before_data
		{
			get
			{
				return this._best_before_data;
			}
			set
			{
				if ((this._best_before_data != value))
				{
					this.Onbest_before_dataChanging(value);
					this.SendPropertyChanging();
					this._best_before_data = value;
					this.SendPropertyChanged("best_before_data");
					this.Onbest_before_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_used_data", DbType="NVarChar(50)")]
		public string used_data
		{
			get
			{
				return this._used_data;
			}
			set
			{
				if ((this._used_data != value))
				{
					this.Onused_dataChanging(value);
					this.SendPropertyChanging();
					this._used_data = value;
					this.SendPropertyChanged("used_data");
					this.Onused_dataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nutritional", DbType="NVarChar(MAX)")]
		public string nutritional
		{
			get
			{
				return this._nutritional;
			}
			set
			{
				if ((this._nutritional != value))
				{
					this.OnnutritionalChanging(value);
					this.SendPropertyChanging();
					this._nutritional = value;
					this.SendPropertyChanged("nutritional");
					this.OnnutritionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_produced", DbType="NVarChar(MAX)")]
		public string produced
		{
			get
			{
				return this._produced;
			}
			set
			{
				if ((this._produced != value))
				{
					this.OnproducedChanging(value);
					this.SendPropertyChanging();
					this._produced = value;
					this.SendPropertyChanged("produced");
					this.OnproducedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark3", DbType="NVarChar(MAX)")]
		public string remark3
		{
			get
			{
				return this._remark3;
			}
			set
			{
				if ((this._remark3 != value))
				{
					this.Onremark3Changing(value);
					this.SendPropertyChanging();
					this._remark3 = value;
					this.SendPropertyChanged("remark3");
					this.Onremark3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark4", DbType="NVarChar(MAX)")]
		public string remark4
		{
			get
			{
				return this._remark4;
			}
			set
			{
				if ((this._remark4 != value))
				{
					this.Onremark4Changing(value);
					this.SendPropertyChanging();
					this._remark4 = value;
					this.SendPropertyChanged("remark4");
					this.Onremark4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark5", DbType="NVarChar(MAX)")]
		public string remark5
		{
			get
			{
				return this._remark5;
			}
			set
			{
				if ((this._remark5 != value))
				{
					this.Onremark5Changing(value);
					this.SendPropertyChanging();
					this._remark5 = value;
					this.SendPropertyChanged("remark5");
					this.Onremark5Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark6", DbType="NVarChar(MAX)")]
		public string remark6
		{
			get
			{
				return this._remark6;
			}
			set
			{
				if ((this._remark6 != value))
				{
					this.Onremark6Changing(value);
					this.SendPropertyChanging();
					this._remark6 = value;
					this.SendPropertyChanged("remark6");
					this.Onremark6Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark7", DbType="NVarChar(MAX)")]
		public string remark7
		{
			get
			{
				return this._remark7;
			}
			set
			{
				if ((this._remark7 != value))
				{
					this.Onremark7Changing(value);
					this.SendPropertyChanging();
					this._remark7 = value;
					this.SendPropertyChanged("remark7");
					this.Onremark7Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_remark8", DbType="NVarChar(MAX)")]
		public string remark8
		{
			get
			{
				return this._remark8;
			}
			set
			{
				if ((this._remark8 != value))
				{
					this.Onremark8Changing(value);
					this.SendPropertyChanging();
					this._remark8 = value;
					this.SendPropertyChanged("remark8");
					this.Onremark8Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Images", DbType="NVarChar(MAX)")]
		public string Images
		{
			get
			{
				return this._Images;
			}
			set
			{
				if ((this._Images != value))
				{
					this.OnImagesChanging(value);
					this.SendPropertyChanging();
					this._Images = value;
					this.SendPropertyChanged("Images");
					this.OnImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_freeimage", DbType="NVarChar(MAX)")]
		public string freeimage
		{
			get
			{
				return this._freeimage;
			}
			set
			{
				if ((this._freeimage != value))
				{
					this.OnfreeimageChanging(value);
					this.SendPropertyChanging();
					this._freeimage = value;
					this.SendPropertyChanged("freeimage");
					this.OnfreeimageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Scales")]
	public partial class Scales : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Shop_id;
		
		private string _Branch_id;
		
		private string _Pos_No;
		
		private string _ScaleGroup;
		
		private string _ScaleName;
		
		private string _IpAddress;
		
		private string _SendPort;
		
		private string _ReceiverPort;
		
		private string _ConnectedState;
		
		private string _Result;
		
		private string _Enable;
		
		private string _Images;
		
		private string _Images1;
		
		private string _Color;
		
		private string _Remark;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnShop_idChanging(string value);
    partial void OnShop_idChanged();
    partial void OnBranch_idChanging(string value);
    partial void OnBranch_idChanged();
    partial void OnPos_NoChanging(string value);
    partial void OnPos_NoChanged();
    partial void OnScaleGroupChanging(string value);
    partial void OnScaleGroupChanged();
    partial void OnScaleNameChanging(string value);
    partial void OnScaleNameChanged();
    partial void OnIpAddressChanging(string value);
    partial void OnIpAddressChanged();
    partial void OnSendPortChanging(string value);
    partial void OnSendPortChanged();
    partial void OnReceiverPortChanging(string value);
    partial void OnReceiverPortChanged();
    partial void OnConnectedStateChanging(string value);
    partial void OnConnectedStateChanged();
    partial void OnResultChanging(string value);
    partial void OnResultChanged();
    partial void OnEnableChanging(string value);
    partial void OnEnableChanged();
    partial void OnImagesChanging(string value);
    partial void OnImagesChanged();
    partial void OnImages1Changing(string value);
    partial void OnImages1Changed();
    partial void OnColorChanging(string value);
    partial void OnColorChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public Scales()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Shop_id", DbType="NVarChar(50)")]
		public string Shop_id
		{
			get
			{
				return this._Shop_id;
			}
			set
			{
				if ((this._Shop_id != value))
				{
					this.OnShop_idChanging(value);
					this.SendPropertyChanging();
					this._Shop_id = value;
					this.SendPropertyChanged("Shop_id");
					this.OnShop_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch_id", DbType="NVarChar(50)")]
		public string Branch_id
		{
			get
			{
				return this._Branch_id;
			}
			set
			{
				if ((this._Branch_id != value))
				{
					this.OnBranch_idChanging(value);
					this.SendPropertyChanging();
					this._Branch_id = value;
					this.SendPropertyChanged("Branch_id");
					this.OnBranch_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pos_No", DbType="NVarChar(50)")]
		public string Pos_No
		{
			get
			{
				return this._Pos_No;
			}
			set
			{
				if ((this._Pos_No != value))
				{
					this.OnPos_NoChanging(value);
					this.SendPropertyChanging();
					this._Pos_No = value;
					this.SendPropertyChanged("Pos_No");
					this.OnPos_NoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScaleGroup", DbType="NVarChar(50)")]
		public string ScaleGroup
		{
			get
			{
				return this._ScaleGroup;
			}
			set
			{
				if ((this._ScaleGroup != value))
				{
					this.OnScaleGroupChanging(value);
					this.SendPropertyChanging();
					this._ScaleGroup = value;
					this.SendPropertyChanged("ScaleGroup");
					this.OnScaleGroupChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScaleName", DbType="NVarChar(50)")]
		public string ScaleName
		{
			get
			{
				return this._ScaleName;
			}
			set
			{
				if ((this._ScaleName != value))
				{
					this.OnScaleNameChanging(value);
					this.SendPropertyChanging();
					this._ScaleName = value;
					this.SendPropertyChanged("ScaleName");
					this.OnScaleNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IpAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IpAddress
		{
			get
			{
				return this._IpAddress;
			}
			set
			{
				if ((this._IpAddress != value))
				{
					this.OnIpAddressChanging(value);
					this.SendPropertyChanging();
					this._IpAddress = value;
					this.SendPropertyChanged("IpAddress");
					this.OnIpAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SendPort", DbType="NVarChar(50)")]
		public string SendPort
		{
			get
			{
				return this._SendPort;
			}
			set
			{
				if ((this._SendPort != value))
				{
					this.OnSendPortChanging(value);
					this.SendPropertyChanging();
					this._SendPort = value;
					this.SendPropertyChanged("SendPort");
					this.OnSendPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiverPort", DbType="NVarChar(50)")]
		public string ReceiverPort
		{
			get
			{
				return this._ReceiverPort;
			}
			set
			{
				if ((this._ReceiverPort != value))
				{
					this.OnReceiverPortChanging(value);
					this.SendPropertyChanging();
					this._ReceiverPort = value;
					this.SendPropertyChanged("ReceiverPort");
					this.OnReceiverPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectedState", DbType="NVarChar(50)")]
		public string ConnectedState
		{
			get
			{
				return this._ConnectedState;
			}
			set
			{
				if ((this._ConnectedState != value))
				{
					this.OnConnectedStateChanging(value);
					this.SendPropertyChanging();
					this._ConnectedState = value;
					this.SendPropertyChanged("ConnectedState");
					this.OnConnectedStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Result", DbType="NVarChar(50)")]
		public string Result
		{
			get
			{
				return this._Result;
			}
			set
			{
				if ((this._Result != value))
				{
					this.OnResultChanging(value);
					this.SendPropertyChanging();
					this._Result = value;
					this.SendPropertyChanged("Result");
					this.OnResultChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enable", DbType="NVarChar(50)")]
		public string Enable
		{
			get
			{
				return this._Enable;
			}
			set
			{
				if ((this._Enable != value))
				{
					this.OnEnableChanging(value);
					this.SendPropertyChanging();
					this._Enable = value;
					this.SendPropertyChanged("Enable");
					this.OnEnableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Images", DbType="NVarChar(MAX)")]
		public string Images
		{
			get
			{
				return this._Images;
			}
			set
			{
				if ((this._Images != value))
				{
					this.OnImagesChanging(value);
					this.SendPropertyChanging();
					this._Images = value;
					this.SendPropertyChanged("Images");
					this.OnImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Images1", DbType="NVarChar(MAX)")]
		public string Images1
		{
			get
			{
				return this._Images1;
			}
			set
			{
				if ((this._Images1 != value))
				{
					this.OnImages1Changing(value);
					this.SendPropertyChanging();
					this._Images1 = value;
					this.SendPropertyChanged("Images1");
					this.OnImages1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Color", DbType="NVarChar(50)")]
		public string Color
		{
			get
			{
				return this._Color;
			}
			set
			{
				if ((this._Color != value))
				{
					this.OnColorChanging(value);
					this.SendPropertyChanging();
					this._Color = value;
					this.SendPropertyChanged("Color");
					this.OnColorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(MAX)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
